### ISSUE TITLE
THE "MATRIX_COL_CHANNELS" question

### ISSUE THREAD

**Issue by weekinro** [Cipulot/EC60#1]
![TOA%Z)00T$%8AIQ_B}FF($V](https://github.com/Cipulot/EC60/assets/76437358/37e3192e-4561-42ee-8a03-edac1e667e80)
Hello bro, may I ask how the numbers in the picture were obtained

**Comment by Cipulot** [comment]
The numbers in the list correspond to the channel number of the AMUX going from Col0 --> Colx.

**Comment by weekinro** [comment]
> @weekinro列表中的数字对应于从 Col0 --> Col0 开始的 AMUX 的通道号。科尔克斯。

thank you very much，
